# Auto-generated by compose2nix.

{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."arr-stack-lidarr" = {
    image = "lscr.io/linuxserver/lidarr:latest";
    environment = {
      "PGID" = "1000";
      "PUID" = "1000";
      "TZ" = "America/Los_Angeles";
    };
    volumes = [
      "/home/deatrin/docker_volumes/arr-stack/data/Downloads/sabnzbd/downloads:/downloads:rw"
      "/home/deatrin/docker_volumes/arr-stack/data/music:/music:rw"
      "arr-stack_lidarr:/config:rw"
    ];
    labels = {
      "com.centurylinklabs.watchtower.enable" = "true";
      "homepage.description" = "music";
      "homepage.group" = "Arr-Stack";
      "homepage.href" = "https://lidarr.jennex.dev";
      "homepage.icon" = "lidarr.png";
      "homepage.name" = "Lidarr";
      "traefik.enable" = "true";
      "traefik.http.routers.lidarr-secure.entrypoints" = "websecure";
      "traefik.http.routers.lidarr-secure.tls" = "true";
      "traefik.http.routers.lidarr.rule" = "Host(`lidarr.jennex.dev`)";
      "traefik.http.services.lidarr.loadbalancer.server.port" = "8686";
    };
    log-driver = "journald";
    extraOptions = [
      "--network-alias=lidarr"
      "--network=dokploy-network"
    ];
  };
  systemd.services."docker-arr-stack-lidarr" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-volume-arr-stack_lidarr.service"
    ];
    requires = [
      "docker-volume-arr-stack_lidarr.service"
    ];
    partOf = [
      "docker-compose-arr-stack-root.target"
    ];
    wantedBy = [
      "docker-compose-arr-stack-root.target"
    ];
  };
  virtualisation.oci-containers.containers."arr-stack-prowlarr" = {
    image = "lscr.io/linuxserver/prowlarr:latest";
    environment = {
      "PGID" = "1000";
      "PUID" = "1000";
      "TZ" = "America/Los_Angeles";
    };
    volumes = [
      "arr-stack_prowlarr:/config:rw"
    ];
    labels = {
      "com.centurylinklabs.watchtower.enable" = "true";
      "homepage.description" = "Usenet Indexer";
      "homepage.group" = "Arr-Stack";
      "homepage.href" = "https://prowlarr.jennex.dev";
      "homepage.icon" = "prowlarr.png";
      "homepage.name" = "Prowlarr";
      "traefik.enable" = "true";
      "traefik.http.routers.prowlarr-secure.entrypoints" = "websecure";
      "traefik.http.routers.prowlarr-secure.tls" = "true";
      "traefik.http.routers.prowlarr.rule" = "Host(`prowlarr.jennex.dev`)";
      "traefik.http.services.prowlarr.loadbalancer.server.port" = "9696";
    };
    log-driver = "journald";
    extraOptions = [
      "--network-alias=prowlarr"
      "--network=dokploy-network"
    ];
  };
  systemd.services."docker-arr-stack-prowlarr" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-volume-arr-stack_prowlarr.service"
    ];
    requires = [
      "docker-volume-arr-stack_prowlarr.service"
    ];
    partOf = [
      "docker-compose-arr-stack-root.target"
    ];
    wantedBy = [
      "docker-compose-arr-stack-root.target"
    ];
  };
  virtualisation.oci-containers.containers."arr-stack-radarr" = {
    image = "lscr.io/linuxserver/radarr:latest";
    environment = {
      "PGID" = "1000";
      "PUID" = "1000";
      "TZ" = "America/Los_Angeles";
    };
    volumes = [
      "/home/deatrin/docker_volumes/arr-stack/data/Downloads/sabnzbd/downloads:/downloads:rw"
      "/home/deatrin/docker_volumes/arr-stack/data/movies:/movies:rw"
      "arr-stack_radarr:/config:rw"
    ];
    labels = {
      "com.centurylinklabs.watchtower.enable" = "true";
      "homepage.description" = "Movies";
      "homepage.group" = "Arr-Stack";
      "homepage.href" = "https://radarr.jennex.dev";
      "homepage.icon" = "radarr.png";
      "homepage.name" = "Radarr";
      "traefik.enable" = "true";
      "traefik.http.routers.radarr-secure.entrypoints" = "websecure";
      "traefik.http.routers.radarr-secure.tls" = "true";
      "traefik.http.routers.radarr.rule" = "Host(`radarr.jennex.dev`)";
      "traefik.http.services.radarr.loadbalancer.server.port" = "7878";
    };
    log-driver = "journald";
    extraOptions = [
      "--network-alias=radarr"
      "--network=dokploy-network"
    ];
  };
  systemd.services."docker-arr-stack-radarr" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-volume-arr-stack_radarr.service"
    ];
    requires = [
      "docker-volume-arr-stack_radarr.service"
    ];
    partOf = [
      "docker-compose-arr-stack-root.target"
    ];
    wantedBy = [
      "docker-compose-arr-stack-root.target"
    ];
  };
  virtualisation.oci-containers.containers."arr-stack-sabnzbd" = {
    image = "lscr.io/linuxserver/sabnzbd:latest";
    environment = {
      "PGID" = "1000";
      "PUID" = "1000";
      "TZ" = "America/Los_Angeles";
    };
    volumes = [
      "/home/deatrin/docker_volumes/arr-stack/data/Downloads/sabnzbd/downloads:/downloads:rw"
      "/home/deatrin/docker_volumes/arr-stack/data/Downloads/sabnzbd/incomplete/downloads:/incomplete-downloads:rw"
      "/home/deatrin/docker_volumes/arr-stack/sabnzbd:/config:rw"
    ];
    labels = {
      "com.centurylinklabs.watchtower.enable" = "true";
      "homepage.description" = "Downloader";
      "homepage.group" = "Arr-Stack";
      "homepage.href" = "https://sabnzbd.jennex.dev";
      "homepage.icon" = "sabnzbd.png";
      "homepage.name" = "Sabnzbd";
      "traefik.enable" = "true";
      "traefik.http.routers.sabnzbd-secure.entrypoints" = "websecure";
      "traefik.http.routers.sabnzbd-secure.tls" = "true";
      "traefik.http.routers.sabnzbd.rule" = "Host(`sabnzbd.jennex.dev`)";
      "traefik.http.services.sabnzbd.loadbalancer.server.port" = "8080";
    };
    log-driver = "journald";
    extraOptions = [
      "--network-alias=sabnzbd"
      "--network=dokploy-network"
    ];
  };
  systemd.services."docker-arr-stack-sabnzbd" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    partOf = [
      "docker-compose-arr-stack-root.target"
    ];
    wantedBy = [
      "docker-compose-arr-stack-root.target"
    ];
  };
  virtualisation.oci-containers.containers."arr-stack-sonarr" = {
    image = "lscr.io/linuxserver/sonarr:latest";
    environment = {
      "PGID" = "1000";
      "PUID" = "1000";
      "TZ" = "America/Los_Angeles";
    };
    volumes = [
      "/home/deatrin/docker_volumes/arr-stack/data/Downloads/sabnzbd/downloads:/downloads:rw"
      "/home/deatrin/docker_volumes/arr-stack/data/tvseries:/tv:rw"
      "arr-stack_sonarr:/config:rw"
    ];
    labels = {
      "com.centurylinklabs.watchtower.enable" = "true";
      "homepage.description" = "TV Shows";
      "homepage.group" = "Arr-Stack";
      "homepage.href" = "https://sonarr.jennex.dev";
      "homepage.icon" = "sonarr.png";
      "homepage.name" = "Sonarr";
      "traefik.enable" = "true";
      "traefik.http.routers.sonarr-secure.entrypoints" = "websecure";
      "traefik.http.routers.sonarr-secure.tls" = "true";
      "traefik.http.routers.sonarr.rule" = "Host(`sonarr.jennex.dev`)";
      "traefik.http.services.sonarr.loadbalancer.server.port" = "8989";
    };
    log-driver = "journald";
    extraOptions = [
      "--network-alias=sonarr"
      "--network=dokploy-network"
    ];
  };
  systemd.services."docker-arr-stack-sonarr" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-volume-arr-stack_sonarr.service"
    ];
    requires = [
      "docker-volume-arr-stack_sonarr.service"
    ];
    partOf = [
      "docker-compose-arr-stack-root.target"
    ];
    wantedBy = [
      "docker-compose-arr-stack-root.target"
    ];
  };
  virtualisation.oci-containers.containers."arr-stack-whisparr" = {
    image = "ghcr.io/hotio/whisparr:latest";
    environment = {
      "PGID" = "1000";
      "PUID" = "1000";
      "TZ" = "America/Los_Angeles";
    };
    volumes = [
      "/home/deatrin/docker_volumes/arr-stack/data/Downloads/sabnzbd/downloads:/downloads:rw"
      "/home/deatrin/docker_volumes/arr-stack/data/whisparr/data:/data:rw"
      "arr-stack_whisparr:/config:rw"
    ];
    labels = {
      "com.centurylinklabs.watchtower.enable" = "true";
      "homepage.description" = "Shhhh";
      "homepage.group" = "Arr-Stack";
      "homepage.href" = "https://whisparr.jennex.dev";
      "homepage.icon" = "whisparr.png";
      "homepage.name" = "Whisparr";
      "traefik.enable" = "true";
      "traefik.http.routers.whisparr-secure.entrypoints" = "websecure";
      "traefik.http.routers.whisparr-secure.tls" = "true";
      "traefik.http.routers.whisparr.rule" = "Host(`whisparr.jennex.dev`)";
      "traefik.http.services.whisparr.loadbalancer.server.port" = "6969";
    };
    log-driver = "journald";
    extraOptions = [
      "--network-alias=whisparr"
      "--network=dokploy-network"
    ];
  };
  systemd.services."docker-arr-stack-whisparr" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-volume-arr-stack_whisparr.service"
    ];
    requires = [
      "docker-volume-arr-stack_whisparr.service"
    ];
    partOf = [
      "docker-compose-arr-stack-root.target"
    ];
    wantedBy = [
      "docker-compose-arr-stack-root.target"
    ];
  };

  # Volumes
  systemd.services."docker-volume-arr-stack_lidarr" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      docker volume inspect arr-stack_lidarr || docker volume create arr-stack_lidarr --driver=local
    '';
    partOf = [ "docker-compose-arr-stack-root.target" ];
    wantedBy = [ "docker-compose-arr-stack-root.target" ];
  };
  systemd.services."docker-volume-arr-stack_prowlarr" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      docker volume inspect arr-stack_prowlarr || docker volume create arr-stack_prowlarr --driver=local
    '';
    partOf = [ "docker-compose-arr-stack-root.target" ];
    wantedBy = [ "docker-compose-arr-stack-root.target" ];
  };
  systemd.services."docker-volume-arr-stack_radarr" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      docker volume inspect arr-stack_radarr || docker volume create arr-stack_radarr --driver=local
    '';
    partOf = [ "docker-compose-arr-stack-root.target" ];
    wantedBy = [ "docker-compose-arr-stack-root.target" ];
  };
  systemd.services."docker-volume-arr-stack_sonarr" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      docker volume inspect arr-stack_sonarr || docker volume create arr-stack_sonarr --driver=local
    '';
    partOf = [ "docker-compose-arr-stack-root.target" ];
    wantedBy = [ "docker-compose-arr-stack-root.target" ];
  };
  systemd.services."docker-volume-arr-stack_whisparr" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      docker volume inspect arr-stack_whisparr || docker volume create arr-stack_whisparr --driver=local
    '';
    partOf = [ "docker-compose-arr-stack-root.target" ];
    wantedBy = [ "docker-compose-arr-stack-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-arr-stack-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
