# File Browser Quantum — web-based file manager for /storage/media/music cleanup
#
# The original filebrowser/filebrowser project is archived 2026-09-01 (no
# further releases or security fixes). gtsteffaniak/filebrowser ("File
# Browser Quantum") is the actively maintained fork the community moved to
# — same lineage, config-driven rather than env-var driven.
#
# Secrets required (via op-connect-secrets, see hosts/nixos/nauvoo/secrets.nix):
#   /run/opnix/filebrowser-admin-password — admin login password
#     1Password: op://nix_secrets/filebrowser/admin_password
#     Any long random string (e.g. `openssl rand -base64 32`), same as any
#     other app-secret in this repo — this isn't auto-generated by Nix.
#     Username is fixed at "admin" (set in config.yaml below).
{
  flake.modules.nixos.filebrowser = {
    config,
    pkgs,
    lib,
    ...
  }: let
    cfg = config.dotfiles.filebrowser;
    inherit (config.virtualisation.quadlet) networks;

    configYaml = pkgs.writeText "filebrowser-config.yaml" ''
      server:
        port: 8080
        sources:
          - path: "/music"
            name: "Music"
            config:
              defaultEnabled: true
      auth:
        adminUsername: "admin"
        adminPassword: "__ADMIN_PASSWORD__"
    '';
  in {
    options.dotfiles.filebrowser.enable = lib.mkEnableOption "File Browser Quantum web file manager (music library)";

    config = lib.mkIf cfg.enable {
      systemd.tmpfiles.rules = [
        "d /var/lib/filebrowser 0755 1000 1000 -"
        "d /var/lib/filebrowser/data 0755 1000 1000 -"
      ];

      # config.yaml lives in the Nix store (world-readable), so the admin
      # password is templated in at activation instead of baked in.
      systemd.services.filebrowser-config-setup = {
        description = "Deploy File Browser config with admin password substituted";
        after = ["opnix-secrets.service"];
        requires = ["opnix-secrets.service"];
        before = ["filebrowser.service"];
        wantedBy = ["filebrowser.service"];
        serviceConfig = {
          Type = "oneshot";
          RemainAfterExit = true;
          ExecStart = lib.getExe (pkgs.writeShellApplication {
            name = "filebrowser-config-setup";
            runtimeInputs = [pkgs.gnused];
            text = ''
              install -m 600 -o 1000 -g 1000 ${configYaml} /var/lib/filebrowser/data/config.yaml
              sed -i "s|__ADMIN_PASSWORD__|$(cat /run/opnix/filebrowser-admin-password)|" /var/lib/filebrowser/data/config.yaml
            '';
          });
        };
      };

      virtualisation.quadlet.containers.filebrowser = {
        unitConfig = {
          After = ["opnix-secrets.service" "filebrowser-config-setup.service"];
          Requires = ["opnix-secrets.service" "filebrowser-config-setup.service"];
        };
        containerConfig = {
          image = "docker.io/gtstef/filebrowser:stable-slim";
          autoUpdate = "registry";
          networks = [networks.traefik_network.ref];
          user = "1000:1000";
          volumes = [
            "/var/lib/filebrowser/data:/home/filebrowser/data"
            "/storage/media/music:/music"
          ];
          labels = [
            "homepage.group=Media"
            "homepage.name=File Browser"
            "homepage.icon=filebrowser.png"
            "homepage.href=https://filebrowser.jennex.dev"
            "homepage.description=Music library cleanup"
            "traefik.enable=true"
            "traefik.http.routers.filebrowser.rule=Host(`filebrowser.jennex.dev`)"
            "traefik.http.routers.filebrowser-secure.entrypoints=https"
            "traefik.http.routers.filebrowser-secure.rule=Host(`filebrowser.jennex.dev`)"
            "traefik.http.routers.filebrowser-secure.tls=true"
            "traefik.http.services.filebrowser.loadbalancer.server.port=8080"
          ];
        };
      };
    };
  };
}
