# Seedbox — qBittorrent + mousehole behind Proton VPN WireGuard, via gluetun
#
# Switched from Mullvad to Proton VPN (2026-08-12) — Mullvad no longer offers
# port forwarding, which qBittorrent needs for good seeding/ratio.
#
# Secrets required (via op-connect-secrets, see hosts/nixos/nauvoo/secrets.nix):
#   /run/opnix/seedbox-wireguard-conf     — full Proton VPN WireGuard .conf file contents
#     1Password: op://nix_secrets/seedbox/conf
#     Generate at https://account.protonvpn.com/downloads (WireGuard configuration) —
#     under "Select VPN options" you MUST enable "NAT-PMP (Port Forwarding)"
#     (and ideally "Moderate NAT") before downloading, or port forwarding
#     silently does nothing. Paste the whole wg-quick .conf file into that
#     field — seedbox-env-setup parses PrivateKey/Address out of it for
#     gluetun, which dials the actual Proton server itself (see
#     SERVER_COUNTRIES below), so the [Peer] section of the file is unused.
#   /run/opnix/seedbox-mousehole-password — mousehole WebUI auth password
#     1Password: op://nix_secrets/seedbox/mousehole_password
#     Any long random string (e.g. `openssl rand -base64 32`), same as any
#     other app-secret in this repo — this isn't auto-generated by Nix.
#
# Port forwarding: gluetun's forwarded port changes on every reconnect, so
# qbtPortSyncScript pushes it into qBittorrent via its WebUI API on every
# change (VPN_PORT_FORWARDING_UP/DOWN_COMMAND). Requires a one-time manual
# qBittorrent setting: Tools > Options > WebUI > Authentication > check
# "Bypass authentication for clients on localhost" — gluetun's request comes
# from 127.0.0.1 (shared netns with qbittorrent), and without that box
# checked qBittorrent just 403s the port-update call.
#
# gluetun is the only container that joins a Podman network — it's the
# Proton VPN gateway and kill switch. qbittorrent and mousehole have no
# network of their own: they ride gluetun's network namespace
# (--network=container:gluetun), so if the tunnel drops, both lose all
# connectivity outright. Because of that, Traefik routing labels for both
# live on gluetun (pointing at their respective WebUI ports), not on
# qbittorrent/mousehole themselves.
#
# qBittorrent is not auto-registered as a download client — add it manually
# in each *arr's Settings > Download Clients (host: qbittorrent, port: 8080).
# Shares /storage/media/downloads/qbittorrent with sonarr/radarr/lidarr (see
# arr-stack.nix) so completed torrents can be hardlinked instead of copied.
{
  flake.modules.nixos.seedbox = {
    config,
    pkgs,
    lib,
    ...
  }: let
    cfg = config.dotfiles.seedbox;
    inherit (config.virtualisation.quadlet) networks volumes;

    # $1 = port (0 to clear), $2 = interface ("lo" to clear)
    qbtPortSyncScript = pkgs.writeText "qbt-port-sync.sh" ''
      #!/bin/sh
      set -eu
      port="$1"
      interface="$2"
      wget -O- -nv --retry-connrefused \
        --post-data "json={\"listen_port\":$port,\"current_network_interface\":\"$interface\",\"random_port\":false,\"upnp\":false}" \
        http://127.0.0.1:8080/api/v2/app/setPreferences
    '';
  in {
    options.dotfiles.seedbox.enable = lib.mkEnableOption "Seedbox (qBittorrent behind Proton VPN via gluetun)";

    config = lib.mkIf cfg.enable {
      systemd.tmpfiles.rules = [
        "d /storage/media/downloads/qbittorrent 0775 1000 1000 -"
      ];

      systemd.services.seedbox-env-setup = {
        description = "Build seedbox environment files from secrets";
        after = ["opnix-secrets.service"];
        requires = ["opnix-secrets.service"];
        before = ["gluetun.service" "mousehole.service"];
        wantedBy = ["gluetun.service" "mousehole.service"];
        serviceConfig = {
          Type = "oneshot";
          RemainAfterExit = true;
          ExecStart = lib.getExe (pkgs.writeShellApplication {
            name = "seedbox-env-setup";
            text = ''
              conf=/run/opnix/seedbox-wireguard-conf
              private_key=$(grep -m1 -E '^[[:space:]]*PrivateKey' "$conf" | sed -E 's/^[[:space:]]*PrivateKey[[:space:]]*=[[:space:]]*//' | tr -d '[:space:]')
              address=$(grep -m1 -E '^[[:space:]]*Address' "$conf" | sed -E 's/^[[:space:]]*Address[[:space:]]*=[[:space:]]*//' | tr -d '[:space:]')
              {
                printf 'WIREGUARD_PRIVATE_KEY=%s\n' "$private_key"
                printf 'WIREGUARD_ADDRESSES=%s\n'   "$address"
              } > /run/opnix/seedbox-env
              chmod 600 /run/opnix/seedbox-env

              printf 'MOUSEHOLE_AUTH_PASSWORD=%s\n' "$(cat /run/opnix/seedbox-mousehole-password)" > /run/opnix/seedbox-mousehole-env
              chmod 600 /run/opnix/seedbox-mousehole-env
            '';
          });
        };
      };

      virtualisation.quadlet = {
        volumes = {
          seedbox-qbittorrent = {};
          seedbox-mousehole = {};
        };

        containers.gluetun = {
          unitConfig = {
            After = ["opnix-secrets.service" "seedbox-env-setup.service"];
            Requires = ["opnix-secrets.service" "seedbox-env-setup.service"];
          };
          containerConfig = {
            image = "docker.io/qmcgaw/gluetun:latest";
            autoUpdate = "registry";
            networks = [networks.traefik_network.ref];
            environments = {
              VPN_SERVICE_PROVIDER = "protonvpn";
              VPN_TYPE = "wireguard";
              # Adjust to taste — see https://protonvpn.com/vpn-servers
              SERVER_COUNTRIES = "USA";
              # Requires "NAT-PMP (Port Forwarding)" enabled when the .conf was generated
              VPN_PORT_FORWARDING = "on";
              VPN_PORT_FORWARDING_UP_COMMAND = "/bin/sh /scripts/qbt-port-sync.sh {{PORT}} {{VPN_INTERFACE}}";
              VPN_PORT_FORWARDING_DOWN_COMMAND = "/bin/sh /scripts/qbt-port-sync.sh 0 lo";
              FIREWALL_OUTBOUND_SUBNETS = "10.89.6.0/24"; # traefik_network bridge subnet
              TZ = "America/Los_Angeles";
            };
            environmentFiles = ["/run/opnix/seedbox-env"];
            volumes = ["${qbtPortSyncScript}:/scripts/qbt-port-sync.sh:ro"];
            podmanArgs = [
              "--cap-add=NET_ADMIN"
              "--device=/dev/net/tun:/dev/net/tun"
            ];
            labels = [
              "homepage.group=Downloads"
              "homepage.name=qBittorrent"
              "homepage.icon=qbittorrent.png"
              "homepage.href=https://qbittorrent.jennex.dev"
              "homepage.description=Torrent client (Proton VPN)"
              "traefik.enable=true"
              "traefik.http.routers.qbittorrent.rule=Host(`qbittorrent.jennex.dev`)"
              "traefik.http.routers.qbittorrent-secure.entrypoints=https"
              "traefik.http.routers.qbittorrent-secure.rule=Host(`qbittorrent.jennex.dev`)"
              "traefik.http.routers.qbittorrent-secure.tls=true"
              "traefik.http.services.qbittorrent.loadbalancer.server.port=8080"
              "traefik.http.routers.mousehole.rule=Host(`mousehole.jennex.dev`)"
              "traefik.http.routers.mousehole-secure.entrypoints=https"
              "traefik.http.routers.mousehole-secure.rule=Host(`mousehole.jennex.dev`)"
              "traefik.http.routers.mousehole-secure.tls=true"
              "traefik.http.services.mousehole.loadbalancer.server.port=5010"
            ];
          };
        };

        containers.qbittorrent = {
          unitConfig = {
            After = ["gluetun.service"];
            Requires = ["gluetun.service"];
          };
          containerConfig = {
            image = "lscr.io/linuxserver/qbittorrent:latest";
            autoUpdate = "registry";
            environments = {
              PUID = "1000";
              PGID = "1000";
              TZ = "America/Los_Angeles";
              WEBUI_PORT = "8080";
            };
            volumes = [
              "${volumes.seedbox-qbittorrent.ref}:/config"
              "/storage/media/downloads/qbittorrent:/downloads"
            ];
            podmanArgs = ["--network=container:gluetun"];
          };
        };

        containers.mousehole = {
          unitConfig = {
            After = ["gluetun.service" "seedbox-env-setup.service"];
            Requires = ["gluetun.service" "seedbox-env-setup.service"];
          };
          containerConfig = {
            image = "docker.io/tmmrtn/mousehole:latest";
            autoUpdate = "registry";
            environments = {
              TZ = "America/Los_Angeles";
            };
            environmentFiles = ["/run/opnix/seedbox-mousehole-env"];
            volumes = ["${volumes.seedbox-mousehole.ref}:/var/lib/mousehole"];
            podmanArgs = ["--network=container:gluetun"];
          };
        };
      };
    };
  };
}
