# Seedbox — qBittorrent + mousehole (no VPN currently)
#
# VPN (Proton VPN via gluetun) pulled out for now (2026-08-12) — gluetun
# reported the NAT-PMP port forward as successful and qBittorrent had the
# matching listen_port, but qBittorrent's connectivity check still showed
# firewalled, so this reverted to plain unprotected containers until that's
# sorted out. To resume: gluetun joined traefik_network directly, qbittorrent
# and mousehole rode its netns via podmanArgs = ["--network=container:gluetun"],
# and Traefik labels lived on gluetun (with explicit .service= labels on each
# router, since one container backed two services) rather than on the apps
# themselves. See git history around this date for the full gluetun config
# (VPN_SERVICE_PROVIDER, port-forward sync script, etc).
#
# Secrets required (via op-connect-secrets, see hosts/nixos/nauvoo/secrets.nix):
#   /run/opnix/seedbox-mousehole-password — mousehole WebUI auth password
#     1Password: op://nix_secrets/seedbox/mousehole_password
#     Any long random string (e.g. `openssl rand -base64 32`), same as any
#     other app-secret in this repo — this isn't auto-generated by Nix.
#
# qBittorrent is not auto-registered as a download client — add it manually
# in each *arr's Settings > Download Clients (host: qbittorrent, port: 8080).
# Shares /storage/media/downloads/qbittorrent with sonarr/radarr/lidarr (see
# arr-stack.nix) so completed torrents can be hardlinked instead of copied.
{
  flake.modules.nixos.seedbox = {
    config,
    pkgs,
    lib,
    ...
  }: let
    cfg = config.dotfiles.seedbox;
    inherit (config.virtualisation.quadlet) networks volumes;
  in {
    options.dotfiles.seedbox.enable = lib.mkEnableOption "Seedbox (qBittorrent + mousehole)";

    config = lib.mkIf cfg.enable {
      systemd.tmpfiles.rules = [
        "d /storage/media/downloads/qbittorrent 0775 1000 1000 -"
      ];

      systemd.services.seedbox-env-setup = {
        description = "Build seedbox environment files from secrets";
        after = ["opnix-secrets.service"];
        requires = ["opnix-secrets.service"];
        before = ["mousehole.service"];
        wantedBy = ["mousehole.service"];
        serviceConfig = {
          Type = "oneshot";
          RemainAfterExit = true;
          ExecStart = lib.getExe (pkgs.writeShellApplication {
            name = "seedbox-env-setup";
            text = ''
              printf 'MOUSEHOLE_AUTH_PASSWORD=%s\n' "$(cat /run/opnix/seedbox-mousehole-password)" > /run/opnix/seedbox-mousehole-env
              chmod 600 /run/opnix/seedbox-mousehole-env
            '';
          });
        };
      };

      virtualisation.quadlet = {
        volumes = {
          seedbox-qbittorrent = {};
          seedbox-mousehole = {};
        };

        containers.qbittorrent = {
          containerConfig = {
            image = "lscr.io/linuxserver/qbittorrent:latest";
            autoUpdate = "registry";
            networks = [networks.traefik_network.ref];
            environments = {
              PUID = "1000";
              PGID = "1000";
              TZ = "America/Los_Angeles";
              WEBUI_PORT = "8080";
            };
            # BitTorrent peer port — forward this on your router (TCP+UDP) to
            # nauvoo's LAN IP for inbound peer connections. Must match the
            # port configured in qBittorrent's own Connection settings.
            publishPorts = [
              "0.0.0.0:3880:3880/tcp"
              "0.0.0.0:3880:3880/udp"
            ];
            volumes = [
              "${volumes.seedbox-qbittorrent.ref}:/config"
              "/storage/media/downloads/qbittorrent:/downloads"
            ];
            labels = [
              "homepage.group=Downloads"
              "homepage.name=qBittorrent"
              "homepage.icon=qbittorrent.png"
              "homepage.href=https://qbittorrent.jennex.dev"
              "homepage.description=Torrent client"
              "traefik.enable=true"
              "traefik.http.routers.qbittorrent.rule=Host(`qbittorrent.jennex.dev`)"
              "traefik.http.routers.qbittorrent-secure.entrypoints=https"
              "traefik.http.routers.qbittorrent-secure.rule=Host(`qbittorrent.jennex.dev`)"
              "traefik.http.routers.qbittorrent-secure.tls=true"
              "traefik.http.services.qbittorrent.loadbalancer.server.port=8080"
            ];
          };
        };

        containers.mousehole = {
          unitConfig = {
            After = ["seedbox-env-setup.service"];
            Requires = ["seedbox-env-setup.service"];
          };
          containerConfig = {
            image = "docker.io/tmmrtn/mousehole:latest";
            autoUpdate = "registry";
            networks = [networks.traefik_network.ref];
            environments = {
              TZ = "America/Los_Angeles";
              # Traefik forwards Host/Origin as mousehole.jennex.dev — mousehole
              # 404s reverse-proxied requests unless both are explicitly allowed
              MOUSEHOLE_ALLOWED_HOSTS = "localhost,127.0.0.1,mousehole.jennex.dev";
              MOUSEHOLE_ALLOWED_ORIGINS = "http://localhost:5010,http://127.0.0.1:5010,https://mousehole.jennex.dev";
            };
            environmentFiles = ["/run/opnix/seedbox-mousehole-env"];
            volumes = ["${volumes.seedbox-mousehole.ref}:/var/lib/mousehole"];
            labels = [
              "traefik.enable=true"
              "traefik.http.routers.mousehole.rule=Host(`mousehole.jennex.dev`)"
              "traefik.http.routers.mousehole-secure.entrypoints=https"
              "traefik.http.routers.mousehole-secure.rule=Host(`mousehole.jennex.dev`)"
              "traefik.http.routers.mousehole-secure.tls=true"
              "traefik.http.services.mousehole.loadbalancer.server.port=5010"
            ];
          };
        };
      };
    };
  };
}
