# Self-hosted Nix binary cache (Attic). nauvoo runs the server, pushes its own
# builds to it (post-build-hook below), and is otherwise the only pusher —
# other machines just pull, via the attic-client.nix aspect.
{
  flake.modules.nixos.attic-server = {
    config,
    lib,
    pkgs,
    inputs,
    ...
  }: let
    cfg = config.dotfiles.attic-server;
    # Not secret — only references the opnix-delivered token *path* (the
    # attic-client aspect's atticToken secret), not the token itself.
    pushConfigToml = pkgs.writeText "attic-client-config.toml" ''
      default-server = "nauvoo"

      [servers.nauvoo]
      endpoint = "https://cache.jennex.dev/"
      token-file = "/run/opnix/attic-token"
    '';
  in {
    options.dotfiles.attic-server.enable = lib.mkEnableOption "self-hosted Attic Nix binary cache server";

    imports = [inputs.attic.nixosModules.atticd];

    config = lib.mkIf cfg.enable {
      # Plain static user instead of the module's default DynamicUser — DynamicUser's
      # ProtectSystem=strict hardening fights writing storage to /ssdstorage (a disk
      # outside /var/lib), and every other nauvoo service already uses a fixed user.
      users.users.atticd = {
        isSystemUser = true;
        group = "atticd";
      };
      users.groups.atticd = {};

      systemd.services.atticd.serviceConfig.DynamicUser = lib.mkForce false;

      # opnix delivers the raw base64 value only (no KEY=VALUE wrapping), so build
      # a proper env file from it first — same pattern as traefik-env-setup.
      systemd.services.attic-server-env-setup = {
        description = "Build atticd environment file from secrets";
        after = ["opnix-secrets.service"];
        requires = ["opnix-secrets.service"];
        before = ["atticd.service"];
        wantedBy = ["atticd.service"];
        serviceConfig = {
          Type = "oneshot";
          RemainAfterExit = true;
          ExecStart = lib.getExe (pkgs.writeShellApplication {
            name = "attic-server-env-setup";
            text = ''
              printf 'ATTIC_SERVER_TOKEN_RS256_SECRET_BASE64=%s\n' \
                "$(cat /run/opnix/attic-server-secret)" > /run/opnix/attic-env
              chmod 600 /run/opnix/attic-env
            '';
          });
        };
      };

      systemd.services.atticd.after = ["attic-server-env-setup.service"];
      systemd.services.atticd.requires = ["attic-server-env-setup.service"];

      services.atticd = {
        enable = true;
        user = "atticd";
        group = "atticd";
        # Generated by attic-server-env-setup.service above, from the raw
        # base64 RSA key: nix run nixpkgs#openssl -- genrsa -traditional 4096 | base64 -w0
        environmentFile = "/run/opnix/attic-env";

        settings = {
          # 0.0.0.0, not 127.0.0.1 — the Traefik quadlet container reaches this over
          # nauvoo's LAN IP, not loopback (same gotcha as code-server).
          listen = "0.0.0.0:8081";
          api-endpoint = "https://cache.jennex.dev/";

          database.url = "sqlite:///ssdstorage/attic/server.db?mode=rwc";

          storage = {
            type = "local";
            path = "/ssdstorage/attic";
          };

          chunking = {
            nar-size-threshold = 64 * 1024;
            min-size = 16 * 1024;
            avg-size = 64 * 1024;
            max-size = 256 * 1024;
          };

          compression.type = "zstd";

          garbage-collection = {
            interval = "12 hours";
            default-retention-period = "12 weeks";
          };
        };
      };

      networking.firewall.allowedTCPPorts = [8081];

      # attic (client CLI, for login/push/cache admin) and atticd-atticadm
      # (token minting) — the atticd module doesn't put either on PATH itself.
      environment.systemPackages = [
        inputs.attic.packages.${pkgs.system}.attic-client
        inputs.attic.packages.${pkgs.system}.attic-server
      ];

      # Auto-push every local build to the cache. post-build-hook runs as the
      # nix-daemon's own user (root) — pin HOME so the attic CLI's XDG config
      # lookup (~/.config/attic/config.toml) resolves deterministically rather
      # than depending on whatever environment nix-daemon.service happens to have.
      systemd.services.nix-daemon.environment.HOME = "/root";

      # /ssdstorage/attic is only one level under /ssdstorage — systemd-tmpfiles
      # refuses to walk a second level deeper (e.g. /ssdstorage/attic/storage)
      # because /ssdstorage itself is owned by deatrin, not root, and it treats
      # the deatrin→atticd ownership change as an unsafe path transition once
      # you nest past it. That's also why storage.path above is /ssdstorage/attic
      # directly rather than a storage/ subdirectory under it.
      systemd.tmpfiles.rules = [
        "d /ssdstorage/attic 0750 atticd atticd -"
        "d /root/.config 0700 root root -"
        "d /root/.config/attic 0700 root root -"
        "L+ /root/.config/attic/config.toml - - - - ${pushConfigToml}"
      ];

      nix.settings.post-build-hook = lib.getExe (pkgs.writeShellApplication {
        name = "attic-post-build-hook";
        text = ''
          set -f # disable globbing
          export IFS=' '
          # post-build-hook runs with a minimal PATH, so call attic by its full
          # store path rather than relying on it being findable.
          # shellcheck disable=SC2086 # intentional word-splitting of OUT_PATHS
          exec ${lib.getExe inputs.attic.packages.${pkgs.system}.attic-client} push nauvoo-cache $OUT_PATHS
        '';
      });
    };
  };
}
