"$schema" = "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"
version = 2

[[blocks]]
alignment = "left"
type = "prompt"

  [[blocks.segments]]
  foreground = "#bb9af7"
  style = "plain"
  template = " {{ .UserName }} on "
  type = "session"

  [[blocks.segments]]
  foreground = "#7aa2f7"
  style = "plain"
  template = "󰉋  {{ .Path }} "
  type = "path"

    [blocks.segments.properties]
    folder_separator_icon = "/"
    style = "full"

  [[blocks.segments]]
  foreground = "#7dcfff"
  style = "plain"
  template = " {{ .UpstreamIcon }}{{ .HEAD }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }} "
  type = "git"

    [blocks.segments.properties]
    fetch_stash_count = true
    fetch_upstream_icon = true

[[blocks]]
alignment = "right"
type = "prompt"

  [[blocks.segments]]
  foreground = "#565f89"
  style = "plain"
  template = "{{ .CurrentDate | date \"15:04:05\" }} "
  type = "time"

[transient_prompt]
  foreground = "#7aa2f7"
  background = "transparent"
  template = "Last: {{ now | date \"15:04:05\" }} "

[[blocks]]
alignment = "left"
newline = true
type = "prompt"

  [[blocks.segments]]
  foreground = "#f7768e"
  style = "plain"
  template = "󰓾 "
  type = "root"

  [[blocks.segments]]
  foreground = "#bb9af7"
  style = "plain"
  template = "❯ "
  type = "text"
