{
 "title": "UniFi-Poller: Network Sites - Prometheus",
 "description": "UniFi Poller v2.0 Displays detailed information for network Sites in a UniFi controller using Prometheus.",
 "tags": [
  "unifi",
  "unifi-poller"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "Controller",
    "query": "label_values(unpoller_site_transmit_rate_bytes,source)"
   },
   {
    "name": "Site",
    "query": "label_values(unpoller_site_transmit_rate_bytes{source=~\"$Controller\"},site_name)"
   },
   { "name": "Subsystem", "query": "label_values(subsystem)" },
   { "name": "Smooth", "query": "30s,1m,2m,5m,10m" }
  ]
 },
 "panels": [
  {
   "title": "USW",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(unpoller_site_switches)" }
   ]
  },
  {
   "title": "UAP",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(unpoller_site_aps)" }
   ]
  },
  {
   "title": "USG",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(unpoller_site_gateways)" }
   ]
  },
  {
   "title": "Stations",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(unpoller_site_stations)" }
   ]
  },
  {
   "title": "Information",
   "type": "text",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 0 },
   "options": {
    "content": "Each site contains 5 subsystems: wan, lan, wlan, www, vpn. Each subsystem contains data specific to that system. \nAll subsystems except vpn have data rate. VPN has data transfer though.\nThere's not a ton of juicy info here, and most of it can be gleaned on other the dashboards.\nThe row below is purposely collapsed because some installationd have hundreds of sites. \nLoading them all at once is often not possible.\n"
   }
  },
  { "title": "Site: $Site", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 }, "repeat": "Site" },
  {
   "title": "Uplink Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "unpoller_site_uptime_seconds" }
   ]
  },
  {
   "title": "Item Counts",
   "type": "timeseries",
   "description": "These are counters, totals, but they don't change much so the graph does not show rate.",
   "gridPos": { "h": 11, "w": 18, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "unpoller_site_iots{site_name=~\"$Site\",subsystem=~\"$Subsystem\"}",
     "legendFormat": "{{subsystem}} IoT"
    },
    {
     "expr": "unpoller_site_adopted{site_name=~\"$Site\",subsystem=~\"$Subsystem\"}",
     "legendFormat": "{{subsystem}} Adopted"
    },
    {
     "expr": "unpoller_site_disabled{site_name=~\"$Site\",subsystem=~\"$Subsystem\"}",
     "legendFormat": "{{subsystem}} Disabled"
    },
    {
     "expr": "unpoller_site_disconnected{site_name=~\"$Site\",subsystem=~\"$Subsystem\"}",
     "legendFormat": "{{subsystem}} Disconnected"
    },
    {
     "expr": "unpoller_site_pending{site_name=~\"$Site\",subsystem=~\"$Subsystem\"}",
     "legendFormat": "{{subsystem}} Pending"
    },
    {
     "expr": "unpoller_site_gateways{site_name=~\"$Site\",subsystem=~\"$Subsystem\"}",
     "legendFormat": "{{subsystem}} Gateways"
    },
    {
     "expr": "unpoller_site_switches{site_name=~\"$Site\",subsystem=~\"$Subsystem\"}",
     "legendFormat": "{{subsystem}} Switches"
    },
    {
     "expr": "unpoller_site_intenet_drops_total{site_name=~\"$Site\",subsystem=~\"$Subsystem\"}",
     "legendFormat": "{{subsystem}} Drops"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "unpoller_site_latency_seconds{site_name=~\"$Site\"}"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "unpoller_site_speedtest_ping{site_name=~\"$Site\"}"
    }
   ]
  },
  {
   "title": "Data Transfer",
   "type": "timeseries",
   "description": "Shows data transfer for each subsystem on the site. RX is on the negative axis.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "unpoller_site_transmit_rate_bytes{site_name=~\"$Site\", subsystem=~\"$Subsystem\"}",
     "legendFormat": "{{subsystem}} Tx"
    },
    {
     "expr": "unpoller_site_receive_rate_bytes{site_name=~\"$Site\", subsystem=~\"$Subsystem\"}",
     "legendFormat": "{{subsystem}} Rx"
    }
   ]
  },
  {
   "title": "Client Counts",
   "type": "timeseries",
   "description": "This graphs shows clients connected to the site.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "unpoller_site_users{site_name=~\"$Site\", subsystem=~\"$Subsystem\"}",
     "legendFormat": "{{subsystem}} Users"
    },
    {
     "expr": "unpoller_site_guests{site_name=~\"$Site\", subsystem=~\"$Subsystem\"}",
     "legendFormat": "{{subsystem}} Guests"
    },
    {
     "expr": "unpoller_site_remote_user_active{site_name=~\"$Site\", subsystem=~\"$Subsystem\"}",
     "legendFormat": "{{subsystem}} Active"
    },
    {
     "expr": "unpoller_site_remote_user_inactive{site_name=~\"$Site\", subsystem=~\"$Subsystem\"}",
     "legendFormat": "{{subsystem}} Inactive"
    },
    {
     "expr": "unpoller_site_stations{site_name=~\"$Site\", subsystem=~\"$Subsystem\"}",
     "legendFormat": "{{subsystem}} Stations"
    }
   ]
  },
  {
   "title": "VPN Users Data Rate",
   "type": "timeseries",
   "description": "This graphs shows clients connected to the site.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "rate(unpoller_site_remote_user_transmit_bytes_total{site_name=~\"$Site\"}[$__interval])",
     "legendFormat": "VPN Users Tx"
    },
    {
     "expr": "rate(unpoller_site_remote_user_receive_bytes_total{site_name=~\"$Site\"}[$__interval])",
     "legendFormat": "VPN Users Rx"
    }
   ]
  },
  {
   "title": "Data Transfer by Category",
   "type": "timeseries",
   "description": "This graph only works if DPI is enabled on the controller and DPI collection is enabled in UniFi Poller. Rx is on the negative axis.",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "sum by (category) (rate(unpoller_site_dpi_receive_bytes{site_name=~\"$Site\"}[$__interval]))",
     "legendFormat": "{{category}} Rx"
    },
    {
     "expr": "sum by (category) (rate(unpoller_site_dpi_transmit_bytes{site_name=~\"$Site\"}[$__interval]))",
     "legendFormat": "{{category}} Tx"
    }
   ]
  }
 ]
}